server:
  port: 9095

spring:
  datasource:
    url: jdbc:postgresql://booker-booking-db:5432/booker-booking-db
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}

  data:
    redis:
      host: booker-redis-container
      port: 6379
      database: 1

  kafka:
    bootstrap-servers: booker-kafka:29092
    properties:
      schema.registry.url: http://booker-schema-registry:8081
    consumer:
      group-id: booking-service-prod
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: "true"
        schema.registry.url: http://booker-schema-registry:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://booker-schema-registry:8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server-service:9090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
