server:
  port: 9096

spring:
  datasource:
    url: jdbc:postgresql://localhost:5002/booker-payment-db
    username: admin
    password: password

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-dev
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: "true"
        schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
