server:
  port: 9094

spring:
  datasource:
    url: jdbc:postgresql://booker-product-db:5432/booker-product-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server-service:9090/eureka/

logging:
  level:
    root: info
